### ISSUE TITLE
Code snippet generates a `java:MethodDeclaration` in semantic mode

### ISSUE THREAD

**Issue by juanjux** [bblfsh/java-driver#104]
In Semantic mode, a function that has arguments is of type "java:MethodDeclaration" and if it does not have arguments, its type is "uast:FunctionGroup"

Code:

```java
package pkg;
public class C {
  public void method(final String str) {}
}
```

As per https://github.com/bblfsh/java-driver/issues/104#issuecomment-455243947
> Specifically, removing the `final` keyword from the parameter declaration of `method` makes the problem go away.

Initial code reproducing this is in details.
<details>

```java
package com.couchbase.client.java;

import com.couchbase.client.core.Core;
import com.couchbase.client.java.env.ClusterEnvironment;

import java.util.function.Function;

import static com.couchbase.client.java.AsyncBucket.DEFAULT_SCOPE;
import static com.couchbase.client.java.AsyncUtils.block;

public class Bucket {

  private final AsyncBucket asyncBucket;
  private final ReactiveBucket reactiveBucket;
  private final Core core;
  private final ClusterEnvironment environment;

  Bucket(AsyncBucket asyncBucket) {
    this.asyncBucket = asyncBucket;
    this.reactiveBucket = new ReactiveBucket(asyncBucket);
    this.core = asyncBucket.core();
    this.environment = asyncBucket.environment();
  }

  public AsyncBucket async() {
    return asyncBucket;
  }

  public ReactiveBucket reactive() {
    return reactiveBucket;
  }

  public Scope scope(final String name) {
    return block(asyncBucket.scope(name)
      .thenApply(asyncScope -> new Scope(asyncScope, asyncBucket.name()))
    );
  }

  public Collection defaultCollection() {
    return scope(DEFAULT_SCOPE).defaultCollection();
  }

  public Collection collection(final String name) {
    return scope(DEFAULT_SCOPE).collection(name);
  }
}
```
</details>

<br/>
Once fixed, this should be added to the integration tests.

**Comment by creachadair** [comment]
Specifically this method:

```java
  public Scope scope(final String name) {
    return block(asyncBucket.scope(name)
      .thenApply(asyncScope -> new Scope(asyncScope, asyncBucket.name()))
    );
  }
```

Repro link: http://play.bblf.sh/daschl/d48c3ad4995ae9ec85f2888e0f2587ac/raw/36f03738ed1a5cbe5211f1999e46a3cf14c35b08/Bucket.java

**Comment by creachadair** [comment]
Here is a minimal repro:

```java
package pkg;
public class C {
  public void method(final String str) {}
}
```

Specifically, removing the `final` keyword from the parameter declaration of `method` makes the problem go away.

**Comment by bzz** [comment]
Issue description updated to include short example.

**Comment by bzz** [comment]
Was rised in a [community slack](https://sourced-community.slack.com/archives/C5JAKNM99/p1556530548002900) today again. 

I'm going to look into this later this week.

**Comment by bzz** [comment]
The issue is due to the fact that method argument modifiers array is always [assumed to be `nil`](https://github.com/bblfsh/java-driver/blob/785cd505580d4c263e70e3c5af31c74b22107c89/driver/normalizer/normalizer.go#L151), which is not the case when `final` is there.

Thus transformation `MethodDeclaration` -> `uast:FunctionGroup` does not happen for such cases.
Simples fix is to keep the same behavior of not preserving the modifiers but make the transformation happen.

Subsequent work should be done, introducing a proper schema for this case e.g by adding some extra node as discussed in https://github.com/bblfsh/sdk/issues/361
