### ISSUE TITLE
semantic: string literal escape sequence handing

### ISSUE THREAD

**Issue by bzz** [bblfsh/java-driver#111]
Discovered as part of the https://github.com/bblfsh/bblfshd/issues/268#issuecomment-475046348

Driver fails to parse e.g [this file](https://r8.googlesource.com/r8/+/16e7bf4b4e203d82817952b69456cfb5be4bd529/src/main/java/com/android/tools/r8/ir/code/BasicBlock.java) with `check: key "escapedValue": invalid syntax ("\0")"`

Normalization mapping for semantic mode needs to be updated.

**Comment by bzz** [comment]
There are total 57 `invalid syntax` cases that look similar in bblfsh/bblfshd#268 logs.

```
 grep "language=java$" bblfshd.log | grep "error" | grep -c "invalid syntax"
57
```

All need to be double-checked and taken care of under this issue as most probably have the same root cause (string decoding, similar to https://github.com/bblfsh/javascript-driver/issues/62)

**Comment by bzz** [comment]
Java, in comparison to other languages, seems to have a well-defined and limited number of special escapes for character and string literals:
 - [unicode escapes](https://docs.oracle.com/javase/specs/jls/se9/html/jls-3.html#jls-3.3)
 - [escape sequences](https://docs.oracle.com/javase/specs/jls/se9/html/jls-3.html#jls-3.10.6)

So only the next cases seem to be different with Go: 
 - single octal escape `\0` that Java has for C compatibility (but [Go does not](https://golang.org/ref/spec#Rune_literals))
 - two-digit octal `\01` (has to be always 3 in Go)

(Does not matter, but interesting fact: 3-digit octal in Java can only start with 0 to 3 🤷‍♂️)

**Comment by creachadair** [comment]
> (Does not matter, but interesting fact: 3-digit octal in Java can only start with 0 to 3 🤷‍♂️)

That's because Java defines "byte" as an octet. In C, where a `char` may nor may not be an octet, the leading digit is allowed to have the full range (but—of course—the behaviour is implementation-defined if you write a sequence that is out of range for the concrete type).
