### ISSUE TITLE
NumberLiteral doesn't return token

### ISSUE THREAD

**Issue by smacker** [bblfsh/java-driver#116]
Test script:
```go
package main

import (
	"fmt"

	bblfsh "gopkg.in/bblfsh/client-go.v3"
	"gopkg.in/bblfsh/client-go.v3/tools"
	"gopkg.in/bblfsh/sdk.v2/uast"
	"gopkg.in/bblfsh/sdk.v2/uast/nodes"
)

var content = `public class Test {
  public String foo(int i) {
    if (i == 0) return "Foo!";
  }
}
`

func main() {
	client, err := bblfsh.NewClient("0.0.0.0:9432")
	if err != nil {
		panic(err)
	}

	res, _, err := client.
		NewParseRequest().
		Mode(bblfsh.Annotated).
		Language("java").
		Content(content).
		UAST()
	if err != nil {
		panic(err)
	}

	query := "//*[@role='Literal']"
	it, _ := tools.Filter(res, query)
	for it.Next() {
		n := it.Node().(nodes.Node)
		fmt.Printf("Type: %s, Token: %s\n", uast.TypeOf(n), uast.TokenOf(n))
	}
}
```

Output:
```
$ go run uast/issue/issue.go
Type: NumberLiteral, Token:
Type: StringLiteral, Token: "Foo!"
```

But it has token which is visible in bblfsh/web:
<img width="306" alt="Screenshot 2019-04-16 at 13 37 47" src="https://user-images.githubusercontent.com/406916/56206527-e5c22e00-604c-11e9-8c58-0ef1100fea6f.png">

**Comment by creachadair** [comment]
This looks like maybe a driver bug, as I think the label should be `@token` rather than plain `token`.

**Comment by bzz** [comment]
Indeed seems to be a native driver bug. Thank you for detailed reproducible example @smacker !

**Comment by bzz** [comment]
This is the case of missing annotation.

One thing to notice is that:
 - `boolean` and `number` literals do not have tokens now, but that easy to fix (will submit a PR).
 - `Type` literals like `Test.class` do not have tokens as well, but that is different and most probably is intentional, as actual type is described by the `type: { '@type': "SimpleType", ... }  `sub-tree.

@dennwc thought?

**Comment by dennwc** [comment]
We will have to leave types with no tokens until we embed the whole source to the UAST, or until we implement the token stream.

Nodes down the tree will have it anyway (identifiers that denote the type name, for example).
