### ISSUE TITLE
Docker Images cannot be pulled

### ISSUE THREAD

**Issue by vmg** [bblfsh/java-driver#13]
👋 Hi friendly src-d folks!

I'm trying to play locally with bblfsh, but I can't get a single driver to run. I'm opening this issue on the Java driver since it seems to be more active, but it also applies to Go, Lua, Python and Rust (the ones I've tried so far).

Trying to build the Docker image for the driver (`make build`) fails because the `bblfsh/java-driver-build:latest` image cannot be fetched from the upstream registry.

```
~/src/bblfsh/java-driver master $ bblfsh-sdk prepare-build
~/src/bblfsh/java-driver master $ make build
+ docker build -q -t bblfsh/java-driver-build -f /home/vmg/src/bblfsh/java-driver/.sdk/tmp/tmp.uPHZa5BZeT .
+ docker build -q -t bblfsh/java-driver-build-with-go -f /home/vmg/src/bblfsh/java-driver/.sdk/tmp/tmp.nZbN7Qj7xx .
+ docker build -q -t bblfsh/java-driver:dev-0a6c00 -f /home/vmg/src/bblfsh/java-driver/.sdk/tmp/tmp.f4J63TZy9q .
Sending build context to Docker daemon 1.013 MB
Step 1 : FROM bblfsh/java-driver-build
Pulling repository docker.io/bblfsh/java-driver-build
Error: image bblfsh/java-driver-build:latest not found
/home/vmg/src/bblfsh/java-driver/.sdk/make/rules.mk:75: recipe for target 'bblfsh/java-driver-build-with-go' failed
make: *** [bblfsh/java-driver-build-with-go] Error 1
make: *** Waiting for unfinished jobs....
^C/home/vmg/src/bblfsh/java-driver/.sdk/make/rules.mk:75: recipe for target 'bblfsh/java-driver--dev-0a6c00' failed
make: *** [bblfsh/java-driver--dev-0a6c00] Interrupt
make: *** wait: No child processes.  Stop.
```

Am I doing something wrong? Have the images just not been pushed yet? Or maybe they're pushed but they're private?

Thanks in advance! Looking forward to playing with this. :)

**Comment by mcuadros** [comment]
Can you run: `docker images | grep -i bblfsh`

Is strange because if you read the log, the image that cannot be found was created in the first line of the log. The images aren't at docker hub are build by the make command.

We will take a look as soon I arrive to the hotel. (We are at JonTheBeach)

Thanks for trying it.

**Comment by vmg** [comment]
Ugh! I figured out the issue! I usually run my dev environment with `MAKEFLAGS=-j8` (i.e. 8 concurrent jobs -- really useful for compiling C++), but the Makefile that the `bblfsh-sdk` creates doesn't have its interdependencies properly defined, so when running with `-j8`, some of the Docker steps race with each other.

Running `make -j1 build` fixes the issue and builds all the images sequentially. :sparkles:

This is more-or-less a legitimate issue which could be worth fixing -- ideally the Makefile would understand that the different `docker build` tasks depend on each other, and never allow them to be run concurrently. I'll send a PR to the SDK once I understand better how the build engine works. ❤️
