### ISSUE TITLE
Java driver returns EOF error for the second file

### ISSUE THREAD

**Issue by dennwc** [bblfsh/java-driver#19]
Steps to reproduce:

```bash
docker run --rm --privileged -d -p 9432:9432 bblfsh/server
go run bblfsh.go --lang=java hello.java hello.java
```

Result:

```
processing ./simple.java
status: fatal: [EOF]
```

Go client: [bblfsh.go](https://gist.github.com/dennwc/8d6a69db88cf89438541a49a26e81ad6)
Java file: [hello.java](https://gist.github.com/dennwc/79848719053d56aeeed0f0e5b0d46d14)

**Comment by abeaumont** [comment]
Thanks for reporting!
I've been able to reproduce it.

**Comment by abeaumont** [comment]
May be related with https://github.com/bblfsh/server/issues/26

**Comment by smola** [comment]
Please, verify this is fixed @abeaumont
