### ISSUE TITLE
Offsets are calculated incorrectly

### ISSUE THREAD

**Issue by vmarkovtsev** [bblfsh/java-driver#49]
This hackathon I experienced the wrong offsets of nodes' positions. Line numbers and columns were correct. For example,

```
wget https://raw.githubusercontent.com/zeroturnaround/zt-zip/master/src/main/java/org/zeroturnaround/zip/commons/FileUtils.java
python3 -m bblfsh -f FileUtils.java
```

```
{
      internal_type: "SimpleName"
      properties {
        key: "internalRole"
        value: "name"
      }
      token: "getTempFileFor"
      start_position {
        offset: 1986
        line: 69
        col: 22
      }
      end_position {
        offset: 2000
        line: 69
        col: 36
      }
      roles: EXPRESSION
      roles: IDENTIFIER
      roles: FUNCTION
      roles: NAME
}
```

`getTempFileFor` is line 69, col 36, **offset 1986**. However,

```
grep --byte-offset getTempFileFor FileUtils.java
2033:  public static File getTempFileFor(File file) {
```

The same number is produced by my homebrew utf-8 aware Python3 script. At the same time, the considered file is not unicode-d at all.

```
time="2017-09-27T14:54:17Z" level=info msg="container started bblfsh/java-driver:latest (01BV1X9KXP0HJBG4WYW2MNZZZB)"
```

**Comment by abeaumont** [comment]
Thanks for reporting @vmarkovtsev. I can reproduce it in the python client, but not with the java-driver:
```
.  .  .  .  .  .  4: SimpleName {
.  .  .  .  .  .  .  Roles: Expression,Identifier,Function,Name
.  .  .  .  .  .  .  TOKEN "getTempFileFor"
.  .  .  .  .  .  .  StartPosition: {
.  .  .  .  .  .  .  .  Offset: 2054
.  .  .  .  .  .  .  .  Line: 69
.  .  .  .  .  .  .  .  Col: 22
.  .  .  .  .  .  .  }
.  .  .  .  .  .  .  EndPosition: {
.  .  .  .  .  .  .  .  Offset: 2068
.  .  .  .  .  .  .  .  Line: 69
.  .  .  .  .  .  .  .  Col: 36
.  .  .  .  .  .  .  }
.  .  .  .  .  .  .  Properties: {
.  .  .  .  .  .  .  .  internalRole: name
.  .  .  .  .  .  .  }
.  .  .  .  .  .  }
```

Which probably means that there's some problem with the python client (maybe some problem with the protocol buffers?)
cc @juanjux

**Comment by juanjux** [comment]
I'll check this soon.

**Comment by juanjux** [comment]
Simple test (Python):

Length of the file in bytes is 2328 confirmed by Vim and `wc`.

Now:

```python
f = open("FileUtils.java").read()
len(f)  # 2248 in Python 3 (unicode str), 2328 in Python2 (byte str)
```

The solution is to open the file in binary mode:

```python
f = open("FileUtils.java", "rb").read()
len(f)  # 2328 in all versions
```

I'll do a PR as soon as I test that this doesn't break anything.

**Comment by juanjux** [comment]
Fixed by github.com/bblfsh/client-python/pull/40

**Comment by vmarkovtsev** [comment]
I used this code to send the request: https://github.com/src-d/hercules/blob/uast/uast.go#L164 Does it mean that the problem is always on the client side and I need to fix my code?

**Comment by juanjux** [comment]
That code gave you the wrong offsets? I tested with the client-go and it returned the correct results so using Go should be fine, tell me if that is not the case.

**Comment by vmarkovtsev** [comment]
Yep, this code gave me the wrong offsets. I used it to gather the dataset on the hackathon.

**Comment by vmarkovtsev** [comment]
Looks like I should debug this myself then... Is there a way to detect this unicode issue on the server side?

**Comment by juanjux** [comment]
Don't worry, I'll do a test case based on your code.

**Comment by juanjux** [comment]
@vmarkovtsev I wrote this tests that tries to be similar to your code while still being simple (uses ReadFile to read the file instead of the object.File) and it gives me the right offset (2054) for this specific file:

https://gist.github.com/juanjux/f4294d41b217f21406b605f75f0ccfb4

So I don't really know why Hercules is giving the wrong offset at this point.

**Comment by vmarkovtsev** [comment]
I believe it is related to Git. To reproduce it,

```
git clone https://github.com/zeroturnaround/zt-zip.git
export GOPATH=$(pwd)
mkdir -p src/gopkg.in/src-d
git clone --branch uast src/gopkg.in/src-d/hercules.v2
CGO_CFLAGS="-I/usr/local/include/libuast" CGO_LDFLAGS="-luast -L/usr/local/lib -Wl,-rpath -Wl,/usr/local/lib" go get gopkg.in/src-d/hercules.v2/cmd/hercules
bin/hercules -uasts -uast-pool-size 2 zt-zip
# bloated with files in CWD now
# 100_0_before_*.pb is the serialized UAST with the wrong offsets
```

But I really think it is my job to find out what's wrong. Feel free to close this.

**Comment by juanjux** [comment]
Ok, if you find something we're here to help. I'll close when the other PR is merged.
