### ISSUE TITLE
Code doesn't match method semantic annotation

### ISSUE THREAD

**Issue by juanjux** [bblfsh/java-driver#82]
Code:

```java
class EqualsNotNull {
    public boolean equals(@javax.annotation.Nonnull Object obj) { }
}
```

Error:

        --- FAIL: TestJavaDriver/semantic/equals_notnull (0.01s)
        	fixtures.go:269: blacklisted nodes of type "MethodDeclaration" (1) found in the tree

**Comment by bzz** [comment]
This has been fixed in #104
