### ISSUE TITLE
Empty switch statements aren't supported

### ISSUE THREAD

**Issue by BFergerson** [bblfsh/java-driver#98]
The following is valid Java:
```java
public class EmptySwitch {
    public void emptySwitch() {
        switch (1) {
        }
    }
}
```

However parsing will cause the following error:
```
ParseResponse(FATAL,Vector(transform failed: construct: key "statements": expected list, got <nil>),Some(Duration(0,3095550)),None,java,)
```

I'm still learning Go (mainly through my exposure of bblfsh projects) so I'm not too sure how to solve this one myself but I'm thinking it has something to do with https://github.com/bblfsh/java-driver/blob/54359978e4d3b5999c8b6eefde0f0770b8d8909d/driver/normalizer/annotation.go#L606.

**Comment by dennwc** [comment]
Thanks for tracking this down. This indeed is because UAST transformation code expects an empty array in `statements`  for an empty `switch` statement. Will fix it shortly.
